name: 'Test'
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
 steps:
    - uses: actions/checkout@v4
    - name: 'Report Coverage'
      if: always() 
      uses: sonichigo/go-covreport@main
