name: 'Test'
on: 
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
     - uses: actions/checkout@v4
     - name: 'Report Coverage'
       uses: sonichigo/go-covreport@main
